### ISSUE TITLE
Spanish translation.

### ISSUE THREAD

**Issue by ghost** [Dealtz/eBookReader_for_Symbian3_zh-CN#1]
-What files are used for translation?
-Will the improvements of the application continue?

**Comment by Dealtz** [comment]
> -What files are used for translation?

In 1.07(1), translation in `.qml` files because this single language version didn't content outside `.qm` language package.
In 1.07(0), translation in both `.qml` files and `.qm` language pack. 
For more detail, please see the commit ID of these releases, you can see the diff of files for translation.

> -Will the improvements of the application continue?

This repository only provides the unofficial Chinese version. I am not the developer of this application.
You know, Nokia supported Symbian until 2016 but was no longer accepting either new applications or updates for existing apps into the Nokia Store after January 1st, 2014. So I think the developer or the publisher will not make any update and improvements. As you can see, I finished the translation in 2016 and the latest official version 1.07(2) released at 2013/12/29. But now is 2021.
Sadly.
